//SLeasy3 app test~~~
//console.log(window.location.hash);
$(document).ready(function(e) {
	//alert(SLeasy.is('portrait'))
	//
	var config={
		id:'',
		formId:'myForm',
		slideCount:2,
		host:'images/',
		//musicUrl:'music.mp3',
		//musicBt:[1],//背景音乐按钮[开启状态，sprite图片url，宽度，高度，对齐方式，x轴偏移，y轴偏移]
		width:640,
		height:1092,
		viewport:320,
		stageMode:'auto',
		motionTime:1,
		motionStyle:0,
		loopMode:1,
		alignMode:'top',
		//alignOffset:200,
		swipeMode:'x',
		arrowMode:1,
		arrowColor:'red',
		loaderStyle:1,
		exLoadImg:[
			'images/0301.jpg',
			'images/0302.jpg',
			'images/0303.png',
			'images/t01.png',
			'images/t02.png',
			'images/t03.png',
			'images/t04.png',
			'images/t05.png',
			'images/t06.png',
			'images/t07.png',
			'images/t08.png',
			'images/t09.png',
		],
		
		floats:[
			{
				img:'t01.png',
				set:{display:'block',x:320},
				noDiv:true,
				event:'tap',
				onEvent:function(){SLeasy.goDetail('box')}
			},
		],
		details:[
			//d01==================================================
			{
			label:'box',
			bg:'01.jpg',
			title:'dddddddd',
			set:{height:200,bottom:0},
			subMotion:[
				{
				img:'0101.png',
				time:0.8,
				event:'tap',
				onEvent:function(){SLeasy.closeDetail('box')},
				in:{x:640,y:115,opacity:0,scale:1},
				show:{x:198,y:115,opacity:1,scale:1,ease:Power4.easeInOut}
				},
			]
			},
		
		//details end
		],
		sliders:[
			{
			label:'test',
			bg:'01.jpg',
			title:'11111',
			subMotion:[
				//01=============================================================
				{
				label:'a',
				img:'0101.png',
				time:0.8,
				in:{x:640,y:115,opacity:0,scale:1},
				show:{x:198,y:115,opacity:1,scale:1,ease:Power4.easeInOut},
				},
				{
				label:'b',
				img:'0102.png',
				time:0.6,
				event:'tap',
				onEvent:function(){SLeasy.play('end')},
				in:{x:-50,y:312,opacity:0,scale:1},
				show:{x:20,y:302,opacity:1,scale:1,ease:Power4.easeOut},
				},
				{
				//pause:1,
				img:'0103.png',
				time:0.6,
				start:0.4,
				in:{x:100,y:472,opacity:0,scale:1},
				show:{x:52,y:482,opacity:1,scale:1,ease:Power4.easeOut},
				
				},
				{
				img:'0104.png',
				time:0.6,
				start:0.4,
				in:{x:66,y:666,opacity:0,scale:0},
				show:{x:66,y:666,opacity:1,scale:1,ease:Power4.easeOut},
				},
				{
				//label:'end',
				img:'0105.png',
				time:0.6,
				event:'tap',
				onEvent:function(){
					console.log(SLeasy.label());
					SLeasy.goDetail('box');
				},
				in:{x:30,y:906,opacity:0,scale:1},
				show:{x:30,y:896,opacity:1,scale:1,ease:Power4.easeOut},
				to:[
					{sub:'a',time:1,to:{y:600}},
					{sub:'b',time:1,start:0.3,to:{y:0}}
				]
				},
				]
			},
			
			//02=============================================================
			{
			bg:'02.jpg',
			title:'2222222',
			subMotion:[
				//----0201------------------------------------------------
				{
				img:'g01.png',
				time:0.6,
				event:'tap',
				onEvent:function(){showTxt(0)},
				in:{x:0,y:169,opacity:1,scale:0},
				show:{x:0,y:169,opacity:1,scale:1,ease:Back.easeOut}
				},
				{
				img:'g02.png',
				time:0.6,
				start:0.2,
				event:'tap',
				onEvent:function(){showTxt(1)},
				in:{x:214,y:169,opacity:1,scale:0},
				show:{x:214,y:169,opacity:1,scale:1,ease:Back.easeOut}
				},
				{
				img:'g03.png',
				time:0.6,
				start:0.2,
				event:'tap',
				onEvent:function(){showTxt(2)},
				in:{x:428,y:169,opacity:1,scale:0},
				show:{x:428,y:169,opacity:1,scale:1,ease:Back.easeOut}
				},
				//----0202------------------------------------------------
				{
				img:'g04.png',
				time:0.6,
				start:0.2,
				event:'tap',
				onEvent:function(){showTxt(3)},
				in:{x:0,y:385,opacity:1,scale:0},
				show:{x:0,y:385,opacity:1,scale:1,ease:Back.easeOut}
				},
				{
				img:'g05.png',
				time:0.6,
				start:0.2,
				event:'tap',
				onEvent:function(){showTxt(4)},
				in:{x:214,y:385,opacity:1,scale:0},
				show:{x:214,y:385,opacity:1,scale:1,ease:Back.easeOut}
				},
				{
				img:'g06.png',
				time:0.6,
				start:0.2,
				event:'tap',
				onEvent:function(){showTxt(5)},
				in:{x:428,y:385,opacity:1,scale:0},
				show:{x:428,y:385,opacity:1,scale:1,ease:Back.easeOut}
				},
				//----0203------------------------------------------------
				{
				img:'g07.png',
				time:0.6,
				start:0.2,
				event:'tap',
				onEvent:function(){showTxt(6)},
				in:{x:0,y:600,opacity:1,scale:0},
				show:{x:0,y:600,opacity:1,scale:1,ease:Back.easeOut}
				},
				{
				img:'g08.png',
				time:0.6,
				start:0.2,
				event:'tap',
				onEvent:function(){showTxt(7)},
				in:{x:214,y:600,opacity:1,scale:0},
				show:{x:214,y:600,opacity:1,scale:1,ease:Back.easeOut}
				},
				{
				img:'g09.png',
				time:0.6,
				start:0.2,
				event:'tap',
				onEvent:function(){showTxt(8)},
				in:{x:428,y:600,opacity:1,scale:0},
				show:{x:428,y:600,opacity:1,scale:1,ease:Back.easeOut}
				},
				{
				img:'dot.png',
				time:0.4,
				in:{x:195,y:369,opacity:0,scale:1},
				show:{x:195,y:369,opacity:1,scale:1,ease:Back.easeOut}
				},
				{
				img:'dot.png',
				time:0.4,
				start:0.01,
				in:{x:410,y:369,opacity:0,scale:1},
				show:{x:410,y:369,opacity:1,scale:1,ease:Back.easeOut}
				},
				{
				img:'dot.png',
				time:0.4,
				start:0.01,
				in:{x:195,y:584,opacity:0,scale:1},
				show:{x:195,y:584,opacity:1,scale:1,ease:Back.easeOut}
				},
				{
				img:'dot.png',
				time:0.4,
				start:0.01,
				in:{x:410,y:796,opacity:0,scale:1},
				show:{x:410,y:796,opacity:1,scale:1,ease:Back.easeOut}
				},
				{
				img:'0202.png',
				time:0.6,
				in:{x:0,y:830,opacity:0,scale:1},
				show:{x:0,y:790,opacity:1,scale:1,ease:Back.easeOut,onComplete:function(){
					var dom=$("#SLeasy_subMotion_1_0,#SLeasy_subMotion_1_1,#SLeasy_subMotion_1_2,#SLeasy_subMotion_1_3,#SLeasy_subMotion_1_4,#SLeasy_subMotion_1_5,#SLeasy_subMotion_1_6,#SLeasy_subMotion_1_7,#SLeasy_subMotion_1_8");
				TweenMax.staggerTo(dom,0.8,{opacity:0.6,scale:0.8,ease:Back.easeOut,repeat:1,yoyo:true},0.06);
				}}
				},				
				]	
			},
			
			/*{
			 bgColor:'red',
			 title:'3333333',	
			},
			{
			 bgColor:'yellow',
			 //title:'4444444',	
			},*/
			
		//sliders end		
		],
	}
	//alert($(window).width()+':'+$(window).height());
	SLeasy.init(config).done(function(){
		//alert($(window).width()+':'+$(window).height());
	});
	
	$("#bt").click(function(e) {
		//console.log('+=1');
        SLeasy.goSlider('+=1');
    });
	
	$("#bt2").click(function(e) {
		//console.log('-=1');
        SLeasy.goSlider('-=1');
    });
		
});